name: Kafka

on:
  push:
    branches: [ main ]
    paths:
      - 'kafka/**'
      - '*'
      - '.github/workflows/kafka.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
          check-latest: true

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: kafka:test --continue --no-daemon

      - uses: dorny/test-reporter@v1.5.0
        if: always()
        with:
          name: tests
          path: "kafka/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}
